<div style='color: #216969;
           background-color: #EAF6F6;
           font-size: 200%;
           border-radius:15px;
           text-align:center;
           font-weight:600;
           border-style: solid;
           border-color: dark green;
           font-family: "Cambria";'>
Features Imputation ....
<a class="anchor" id="1"></a>

<img src="https://www.kdnuggets.com/wp-content/uploads/saneesh-r-1.png" width=400>

### Imputation Presentation

In [1]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer

# Create a sample DataFrame with missing values
data = {'A': [1, 2, np.nan, 4],
        'B': ['cat', 'dog', np.nan, 'cat'],
        'C': [5.0, np.nan, 7.0, 8.0]}
df = pd.DataFrame(data)

# Impute missing values using the most frequent strategy
imputer = SimpleImputer(strategy='most_frequent')
df_imputed = pd.DataFrame(imputer.fit_transform(df), columns=df.columns)

In [2]:

print("Original DataFrame:")
df

Original DataFrame:

     A    B    C
0  1.0  cat  5.0
1  2.0  dog  NaN
2  NaN  NaN  7.0
3  4.0  cat  8.0

In [3]:
print("\nImputed DataFrame:")
df_imputed

Imputed DataFrame:

     A    B    C
0  1.0  cat  5.0
1  2.0  dog  5.0
2  1.0  cat  7.0
3  4.0  cat  8.0

### Data Loading

In [5]:
# datset loading
import pandas as pd
df= pd.read_csv("../data/HousePrice4.csv", index_col=0)

In [6]:
df.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,...,ScreenPorch,PoolArea,MiscVal,MoSold,SaleType,SaleCondition,SalePrice,Remodeled,Age,Isnew
Id,,,,,,,,,,,,,,,,,,,,,
1,60,RL,65.0,8450,Pave,3,Lvl,AllPub,Inside,2,...,0,0,0,2,WD,Normal,208500,0,5,0
2,20,RL,80.0,9600,Pave,3,Lvl,AllPub,FR2,2,...,0,0,0,5,WD,Normal,181500,0,31,0
3,60,RL,68.0,11250,Pave,2,Lvl,AllPub,Inside,2,...,0,0,0,9,WD,Normal,223500,1,6,0
4,70,RL,60.0,9550,Pave,2,Lvl,AllPub,Corner,2,...,0,0,0,2,WD,Abnorml,140000,1,36,0
5,60,RL,84.0,14260,Pave,2,Lvl,AllPub,FR2,2,...,0,0,0,12,WD,Normal,250000,0,8,0

![](../imgs/featureEngin.png)

In [7]:
df.shape

(1460, 71)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1460 entries, 1 to 1460
Data columns (total 71 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MSSubClass     1460 non-null   int64
 1   MSZoning       1460 non-null   object
 2   LotFrontage    1201 non-null   float64
 3   LotArea        1460 non-null   int64
 4   Street         1460 non-null   object
 5   LotShape       1460 non-null   int64
 6   LandContour    1460 non-null   object
 7   Utilities      1460 non-null   object
 8   LotConfig      1460 non-null   object
 9   LandSlope      1460 non-null   int64
 10  Neighborhood   1460 non-null   int64
 11  Condition1     1460 non-null   object
 12  Condition2     1460 non-null   object
 13  BldgType       1460 non-null   object
 14  HouseStyle     1460 non-null   object
 15  OverallQual    1460 non-null   int64
 16  OverallCond    1460 non-null   int64
 17  RoofStyle      1460 non-null   object
 18  RoofMatl       1460 non-null   object
 19  Exterior1st    1460 non-null   object
 20  Exterior2nd    1460 non-null   object
 21  MasVnrArea     1452 non-null   float64
 22  ExterQual      1460 non-null   int64
 23  ExterCond      1460 non-null   int64
 24  Foundation     1460 non-null   object
 25  BsmtQual       1423 non-null   float64
 26  BsmtCond       1423 non-null   float64
 27  BsmtExposure   1422 non-null   float64
 28  BsmtFinType1   1423 non-null   float64
 29  BsmtFinSF1     1460 non-null   int64
 30  BsmtFinType2   1422 non-null   float64
 31  BsmtFinSF2     1460 non-null   int64
 32  BsmtUnfSF      1460 non-null   int64
 33  TotalBsmtSF    1460 non-null   int64
 34  Heating        1460 non-null   object
 35  HeatingQC      1460 non-null   int64
 36  CentralAir     1460 non-null   int64
 37  Electrical     1459 non-null   object
 38  2ndFlrSF       1460 non-null   int64
 39  LowQualFinSF   1460 non-null   int64
 40  GrLivArea      1460 non-null   int64
 41  BsmtFullBath   1460 non-null   int64
 42  BsmtHalfBath   1460 non-null   int64
 43  FullBath       1460 non-null   int64
 44  HalfBath       1460 non-null   int64
 45  BedroomAbvGr   1460 non-null   int64
 46  KitchenAbvGr   1460 non-null   int64
 47  KitchenQual    1460 non-null   int64
 48  TotRmsAbvGrd   1460 non-null   int64
 49  Functional     1460 non-null   int64
 50  Fireplaces     1460 non-null   int64
 51  GarageType     1379 non-null   object
 52  GarageFinish   1379 non-null   float64
 53  GarageArea     1460 non-null   int64
 54  GarageQual     1379 non-null   float64
 55  GarageCond     1379 non-null   float64
 56  PavedDrive     1460 non-null   int64
 57  WoodDeckSF     1460 non-null   int64
 58  OpenPorchSF    1460 non-null   int64
 59  EnclosedPorch  1460 non-null   int64
 60  3SsnPorch      1460 non-null   int64
 61  ScreenPorch    1460 non-null   int64
 62  PoolArea       1460 non-null   int64
 63  MiscVal        1460 non-null   int64
 64  MoSold         1460 non-null   int64
 65  SaleType       1460 non-null   object
 66  SaleCondition  1460 non-null   object
 67  SalePrice      1460 non-null   int64
 68  Remodeled      1460 non-null   int64
 69  Age            1460 non-null   int64
 70  Isnew          1460 non-null   int64
dtypes: float64(10), int64(42), object(19)
memory usage: 821.2+ KB

In [9]:
df.select_dtypes(exclude="number").columns

Index(['MSZoning', 'Street', 'LandContour', 'Utilities', 'LotConfig',
       'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'RoofStyle',
       'RoofMatl', 'Exterior1st', 'Exterior2nd', 'Foundation', 'Heating',
       'Electrical', 'GarageType', 'SaleType', 'SaleCondition'],
      dtype='object')

In [10]:
df.select_dtypes(exclude="number").info()

<class 'pandas.core.frame.DataFrame'>
Index: 1460 entries, 1 to 1460
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MSZoning       1460 non-null   object
 1   Street         1460 non-null   object
 2   LandContour    1460 non-null   object
 3   Utilities      1460 non-null   object
 4   LotConfig      1460 non-null   object
 5   Condition1     1460 non-null   object
 6   Condition2     1460 non-null   object
 7   BldgType       1460 non-null   object
 8   HouseStyle     1460 non-null   object
 9   RoofStyle      1460 non-null   object
 10  RoofMatl       1460 non-null   object
 11  Exterior1st    1460 non-null   object
 12  Exterior2nd    1460 non-null   object
 13  Foundation     1460 non-null   object
 14  Heating        1460 non-null   object
 15  Electrical     1459 non-null   object
 16  GarageType     1379 non-null   object
 17  SaleType       1460 non-null   object
 18  SaleCondition  1460 non-null   object
dtypes: object(19)
memory usage: 228.1+ KB

In [11]:
# cast  object types to categorical 
cat_cols = df.select_dtypes(exclude="number").columns
df[cat_cols] = df[cat_cols].astype("category")

In [13]:
df[cat_cols].dtypes

MSZoning         category
Street           category
LandContour      category
Utilities        category
LotConfig        category
Condition1       category
Condition2       category
BldgType         category
HouseStyle       category
RoofStyle        category
RoofMatl         category
Exterior1st      category
Exterior2nd      category
Foundation       category
Heating          category
Electrical       category
GarageType       category
SaleType         category
SaleCondition    category
dtype: object

In [14]:
# dislpay missing values 
miss_val=(df.isna().sum()/df.shape[0]).sort_values()
miss_val.nlargest(5)
#miss_val.nlargest(7).index
# df[miss_val.nlargest(7).index]

LotFrontage     0.177397
GarageCond      0.055479
GarageFinish    0.055479
GarageQual      0.055479
GarageType      0.055479
dtype: float64

In [15]:
df.LotFrontage.isnull().sum()

np.int64(259)

In [16]:
df[df.isna().any(axis=1)]["LotFrontage"].head()

Id
8      NaN
13     NaN
15     NaN
17     NaN
18    72.0
Name: LotFrontage, dtype: float64

In [17]:
# fill missing values 
import numpy as np
pd.Series([1, np.nan, 2, 3 ])

0    1.0
1    NaN
2    2.0
3    3.0
dtype: float64

In [18]:
pd.Series([1, np.nan, 2, 3 ]).fillna(value=0 )

0    1.0
1    0.0
2    2.0
3    3.0
dtype: float64

In [19]:
from sklearn.impute import SimpleImputer
#  strategy :  most_frequent ,   mean , median
# most frequent   for Catgorical Features
? SimpleImputer

Init signature:
 SimpleImputer(
    *,
    missing_values=nan,
    strategy='mean',
    fill_value=None,
    copy=True,
    add_indicator=False,
    keep_empty_features=False,
)
Docstring:
Univariate imputer for completing missing values with simple strategies.

Replace missing values using a descriptive statistic (e.g. mean, median, or
most frequent) along each column, or using a constant value.

Read more in the :ref:`User Guide <impute>`.

.. versionadded:: 0.20
   `SimpleImputer` replaces the previous `sklearn.preprocessing.Imputer`
   estimator which is now removed.

Parameters
----------
missing_values : int, float, str, np.nan, None or pandas.NA, default=np.nan
    The placeholder for the missing values. All occurrences of
    `missing_values` will be imputed. For pandas' dataframes with
    nullable integer dtypes with missing values, `missing_values`
    can be set to either `np.nan` or `pd.NA`.

strategy : str or Callable, default='mean'
    The imputation strategy.

    - If "mean", then replace missing values using the mean along
      each column. Can only be used with numeric data.
    - If "median", then replace missing values using the median along
      each column. Can only be used with numeric data.
    - If "most_frequent", then replace missing using the most frequent
      value along each column. Can be used with strings or numeric data.
      If there is more than one such value, only the smallest is returned.
    - If "constant", then replace missing values with fill_value. Can be
      used with strings or numeric data.
    - If an instance of Callable, then replace missing values using the
      scalar statistic returned by running the callable over a dense 1d
      array containing non-missing values of each column.

    .. versionadded:: 0.20
       strategy="constant" for fixed value imputation.

    .. versionadded:: 1.5
       strategy=callable for custom value imputation.

fill_value : str or numerical value, default=None
    When strategy == "constant", `fill_value` is used to replace all
    occurrences of missing_values. For string or object data types,
    `fill_value` must be a string.
    If `None`, `fill_value` will be 0 when imputing numerical
    data and "missing_value" for strings or object data types.

copy : bool, default=True
    If True, a copy of X will be created. If False, imputation will
    be done in-place whenever possible. Note that, in the following cases,
    a new copy will always be made, even if `copy=False`:

    - If `X` is not an array of floating values;
    - If `X` is encoded as a CSR matrix;
    - If `add_indicator=True`.

add_indicator : bool, default=False
    If True, a :class:`MissingIndicator` transform will stack onto output
    of the imputer's transform. This allows a predictive estimator
    to account for missingness despite imputation. If a feature has no
    missing values at fit/train time, the feature won't appear on
    the missing indicator even if there are missing values at
    transform/test time.

keep_empty_features : bool, default=False
    If True, features that consist exclusively of missing values when
    `fit` is called are returned in results when `transform` is called.
    The imputed value is always `0` except when `strategy="constant"`
    in which case `fill_value` will be used instead.

    .. versionadded:: 1.2

    .. versionchanged:: 1.6
        Currently, when `keep_empty_feature=False` and `strategy="constant"`,
        empty features are not dropped. This behaviour will change in version
        1.8. Set `keep_empty_feature=True` to preserve this behaviour.

Attributes
----------
statistics_ : array of shape (n_features,)
    The imputation fill value for each feature.
    Computing statistics can result in `np.nan` values.
    During :meth:`transform`, features corresponding to `np.nan`
    statistics will be discarded.

indicator_ : :class:`~sklearn.impute.MissingIndicator`
    Indicator used to add binary indicators for missing values.
    `None` if `add_indicator=False`.

n_features_in_ : int
    Number of features seen during :term:`fit`.

    .. versionadded:: 0.24

feature_names_in_ : ndarray of shape (`n_features_in_`,)
    Names of features seen during :term:`fit`. Defined only when `X`
    has feature names that are all strings.

    .. versionadded:: 1.0

See Also
--------
IterativeImputer : Multivariate imputer that estimates values to impute for
    each feature with missing values from all the others.
KNNImputer : Multivariate imputer that estimates missing features using
    nearest samples.

Notes
-----
Columns which only contained missing values at :meth:`fit` are discarded
upon :meth:`transform` if strategy is not `"constant"`.

In a prediction context, simple imputation usually performs poorly when
associated with a weak learner. However, with a powerful learner, it can
lead to as good or better performance than complex imputation such as
:class:`~sklearn.impute.IterativeImputer` or :class:`~sklearn.impute.KNNImputer`.

Examples
--------
>>> import numpy as np
>>> from sklearn.impute import SimpleImputer
>>> imp_mean = SimpleImputer(missing_values=np.nan, strategy='mean')
>>> imp_mean.fit([[7, 2, 3], [4, np.nan, 6], [10, 5, 9]])
SimpleImputer()
>>> X = [[np.nan, 2, 3], [4, np.nan, 6], [10, np.nan, 9]]
>>> print(imp_mean.transform(X))
[[ 7.   2.   3. ]
 [ 4.   3.5  6. ]
 [10.   3.5  9. ]]

For a more detailed example see
:ref:`sphx_glr_auto_examples_impute_plot_missing_values.py`.
File:           /usr/local/python/3.12.1/lib/python3.12/site-packages/sklearn/impute/_base.py
Type:           type
Subclasses:

In [20]:
SimpleImputer(missing_values=np.nan, strategy='most_frequent').fit_transform(pd.DataFrame([1, np.nan, 2, 3, 2 ]))

array([[1.],
       [2.],
       [2.],
       [3.],
       [2.]])

## Imputation  missing values

In [21]:
#  make a copy of the original data
df_cp=df.copy()

In [ ]:
# elliminate features having  missing values
miss_val=(df_cp.isna().sum()/df_cp.shape[0]).sort_values(ascending=False)
miss_val[miss_val>0]

LotFrontage     0.177397
GarageFinish    0.055479
GarageCond      0.055479
GarageQual      0.055479
GarageType      0.055479
BsmtFinType2    0.026027
BsmtExposure    0.026027
BsmtFinType1    0.025342
BsmtCond        0.025342
BsmtQual        0.025342
MasVnrArea      0.005479
Electrical      0.000685
dtype: float64

In [23]:
# display  columns having highest missing values 
miss_val[miss_val>0].index

Index(['LotFrontage', 'GarageFinish', 'GarageCond', 'GarageQual', 'GarageType',
       'BsmtFinType2', 'BsmtExposure', 'BsmtFinType1', 'BsmtCond', 'BsmtQual',
       'MasVnrArea', 'Electrical'],
      dtype='object')

In [24]:

df_cp=df_cp[miss_val[miss_val>0].index] # select only columns having missing values

In [25]:
df_cp.head()

,LotFrontage,GarageFinish,GarageCond,GarageQual,GarageType,BsmtFinType2,BsmtExposure,BsmtFinType1,BsmtCond,BsmtQual,MasVnrArea,Electrical
Id,,,,,,,,,,,,
1,65.0,1.0,2.0,2.0,Attchd,1.0,0.0,5.0,2.0,2.0,196.0,SBrkr
2,80.0,1.0,2.0,2.0,Attchd,1.0,3.0,4.0,2.0,2.0,0.0,SBrkr
3,68.0,1.0,2.0,2.0,Attchd,1.0,1.0,5.0,2.0,2.0,162.0,SBrkr
4,60.0,0.0,2.0,2.0,Detchd,1.0,0.0,4.0,3.0,1.0,0.0,SBrkr
5,84.0,1.0,2.0,2.0,Attchd,1.0,2.0,5.0,2.0,2.0,350.0,SBrkr

In [26]:
df_cp[df_cp.isnull().any(axis=1)].head()

,LotFrontage,GarageFinish,GarageCond,GarageQual,GarageType,BsmtFinType2,BsmtExposure,BsmtFinType1,BsmtCond,BsmtQual,MasVnrArea,Electrical
Id,,,,,,,,,,,,
8,NaN,1.0,2.0,2.0,Attchd,3.0,1.0,4.0,2.0,2.0,240.0,SBrkr
13,NaN,0.0,2.0,2.0,Detchd,1.0,0.0,4.0,2.0,1.0,0.0,SBrkr
15,NaN,1.0,2.0,2.0,Attchd,1.0,0.0,3.0,2.0,1.0,212.0,SBrkr
17,NaN,2.0,2.0,2.0,Attchd,1.0,0.0,4.0,2.0,1.0,180.0,SBrkr
18,72.0,0.0,2.0,2.0,CarPort,NaN,NaN,NaN,NaN,NaN,0.0,SBrkr

In [27]:
df_cp[["LotFrontage"]].mode() #.agg(["min", "max", "mode"]).T

   LotFrontage
0         60.0

In [28]:
from sklearn.impute import SimpleImputer

imput= SimpleImputer(strategy="most_frequent")
df_cp[df_cp.columns]= imput.fit_transform(df_cp)

In [29]:
df_cp[7:16]

,LotFrontage,GarageFinish,GarageCond,GarageQual,GarageType,BsmtFinType2,BsmtExposure,BsmtFinType1,BsmtCond,BsmtQual,MasVnrArea,Electrical
Id,,,,,,,,,,,,
8,60.0,1.0,2.0,2.0,Attchd,3.0,1.0,4.0,2.0,2.0,240.0,SBrkr
9,51.0,0.0,2.0,1.0,Detchd,1.0,0.0,0.0,2.0,1.0,0.0,FuseF
10,50.0,1.0,2.0,3.0,Attchd,1.0,0.0,5.0,2.0,1.0,0.0,SBrkr
11,70.0,0.0,2.0,2.0,Detchd,1.0,0.0,2.0,2.0,1.0,0.0,SBrkr
12,85.0,2.0,2.0,2.0,BuiltIn,1.0,0.0,5.0,2.0,3.0,286.0,SBrkr
13,60.0,0.0,2.0,2.0,Detchd,1.0,0.0,4.0,2.0,1.0,0.0,SBrkr
14,91.0,1.0,2.0,2.0,Attchd,1.0,2.0,0.0,2.0,2.0,306.0,SBrkr
15,60.0,1.0,2.0,2.0,Attchd,1.0,0.0,3.0,2.0,1.0,212.0,SBrkr
16,51.0,0.0,2.0,2.0,Detchd,1.0,0.0,0.0,2.0,1.0,0.0,FuseA

In [ ]:
# we are not saving teh dataset resulted from the imputation because we are going to do it i nanother way later