<div style='color: #216969;
           background-color: #EAF6F6;
           font-size: 200%;
           border-radius:15px;
           text-align:center;
           font-weight:600;
           border-style: solid;
           border-color: dark green;
           font-family: "Cambria";'>
Data Concatenation ....
<a class="anchor" id="1"></a>

In [32]:
# dataset loading df1
import pandas as pd
df1= pd.read_csv("../data/HousePrice4.csv", index_col=0)

In [33]:
# datset import df2
import pandas as pd
df2 = pd.read_csv("../data/features_kept2.csv", index_col=0)

![](../../imgs/featureEngin.png)

In [34]:
df2.head()

,YearBuilt,YearRemodAdd,GarageArea,GrLivArea,MasVnrArea,WoodDeckSF,PoolArea,TotalBsmtSF,ScreenPorch,BsmtFinSF1,SalePrice
0,2003.0,2003.0,548.0,1710.0,196.0,0.0,0.0,856.0,0.0,706.0,208500.0
1,1976.0,1976.0,460.0,1262.0,0.0,298.0,0.0,1262.0,0.0,978.0,181500.0
2,2001.0,2002.0,608.0,1786.0,162.0,0.0,0.0,920.0,0.0,486.0,223500.0
3,1915.0,1970.0,642.0,1717.0,0.0,0.0,0.0,756.0,0.0,216.0,140000.0
4,2000.0,2000.0,836.0,2198.0,350.0,192.0,0.0,1145.0,0.0,655.0,250000.0

In [35]:

# load most important features 
f_select=open("../data/features_selected.txt" , "r").read().split(",")
f_select

['YearBuilt',
 'YearRemodAdd',
 'GarageArea',
 'GrLivArea',
 'MasVnrArea',
 'WoodDeckSF',
 'PoolArea',
 'TotalBsmtSF',
 'ScreenPorch',
 'BsmtFinSF1',
 'SalePrice']

In [36]:
df1.select_dtypes(exclude="number").shape

(1460, 19)

In [37]:
# concatinate selected features with non-numeric features
df_select=pd.concat([df2, df1.select_dtypes(exclude="number")], axis=1)
df_select.head()

,YearBuilt,YearRemodAdd,GarageArea,GrLivArea,MasVnrArea,WoodDeckSF,PoolArea,TotalBsmtSF,ScreenPorch,BsmtFinSF1,...,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,Foundation,Heating,Electrical,GarageType,SaleType,SaleCondition
0,2003.0,2003.0,548.0,1710.0,196.0,0.0,0.0,856.0,0.0,706.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1976.0,1976.0,460.0,1262.0,0.0,298.0,0.0,1262.0,0.0,978.0,...,Gable,CompShg,VinylSd,VinylSd,PConc,GasA,SBrkr,Attchd,WD,Normal
2,2001.0,2002.0,608.0,1786.0,162.0,0.0,0.0,920.0,0.0,486.0,...,Gable,CompShg,MetalSd,MetalSd,CBlock,GasA,SBrkr,Attchd,WD,Normal
3,1915.0,1970.0,642.0,1717.0,0.0,0.0,0.0,756.0,0.0,216.0,...,Gable,CompShg,VinylSd,VinylSd,PConc,GasA,SBrkr,Attchd,WD,Normal
4,2000.0,2000.0,836.0,2198.0,350.0,192.0,0.0,1145.0,0.0,655.0,...,Gable,CompShg,Wd Sdng,Wd Shng,BrkTil,GasA,SBrkr,Detchd,WD,Abnorml

In [38]:
# insert SalePrice column at the end of the datset 

sale=df_select.SalePrice
df_select.drop("SalePrice", axis=1, inplace=True)
df_select["SalePrice"]=sale

In [39]:
df_select.sample(3)

,YearBuilt,YearRemodAdd,GarageArea,GrLivArea,MasVnrArea,WoodDeckSF,PoolArea,TotalBsmtSF,ScreenPorch,BsmtFinSF1,...,RoofMatl,Exterior1st,Exterior2nd,Foundation,Heating,Electrical,GarageType,SaleType,SaleCondition,SalePrice
1167,2000.0,2000.0,472.0,1671.0,0.0,0.0,0.0,959.0,0.0,786.0,...,CompShg,VinylSd,VinylSd,PConc,GasA,SBrkr,Attchd,WD,Normal,173000.0
622,1977.0,1977.0,484.0,980.0,153.0,192.0,0.0,980.0,0.0,560.0,...,CompShg,HdBoard,HdBoard,CBlock,GasA,SBrkr,Attchd,WD,Normal,135000.0
31,1966.0,2006.0,271.0,1228.0,0.0,0.0,0.0,1228.0,0.0,0.0,...,CompShg,BrkFace,BrkFace,BrkTil,GasA,SBrkr,Detchd,WD,Normal,149350.0

In [40]:
df_select.shape

(1461, 30)

In [41]:

# save the dataset 
df_select.to_csv("../data/housePrice_5.csv")